import React from 'react';
import CardList from './CardList';
import SearchBox from './SearchBox';
import Scroll from './Scroll'
// import './app.css';

// const state = {
//     images: images,
//     searchField: ''
// }
const images = [1, 2, 3, 4, 5]

class App extends React.Component {
  constructor() {
    super()
    this.state = {
      robots: [],
      images: images,
      searchField: ''
    }
  }

  componentDidMount() {
    fetch('https://jsonplaceholder.typicode.com/users')
      .then(response => { response.json() })
      .then(users => this.setState({ robots: users }));
  }

  onSearchChange(event) {
    console.log(event.target.value);
  }

  render() {
    const filteredImages = this.state.robots.filter(robots => {
      return robots.name.toLowerCase().includes(this.state.searchfield.toLowerCase())
    })
    
    // If loading to long just show info that work is in progress
    if (this.state.robots.length === 0) {
      return <h1>Loading...</h1>
    }
    else {
      return (
        <div className='tc'>
          <h1 className='f1'>Midjourney most recent interesting arts</h1>
          <p>arts generated by Ai from scratch</p>
          <SearchBox searchChange={this.onSearchChange}/>
          <Scroll>
            <CardList midjourneyImages={filteredImages} />
          </Scroll>
        </div>
      );
    }
  }
}

export default App;
